name = "searchpro-proxy"
main = "worker.js"
compatibility_date = "2023-08-15"

# Keep your account ID
account_id = "51d2fba458de22279e7ea03fabfa0e62"

# Enable development subdomain
workers_dev = true

# Uncomment and configure these when ready for production
# route = "your-domain.com/*"
# zone_id = "your-zone-id"

# Environment variables (if needed)
[vars]
# ENVIRONMENT = "production"

# If you're proxying requests to an origin
[site]
bucket = "./public"  # If you have static assets

# Configure bindings for proxy behavior
[[services]]
binding = "UPSTREAM"
service = "your-upstream-service"

# Control worker placement
[placement]
mode = "smart"
