name = "searchpro-proxy"
main = "worker.js"
compatibility_date = "2023-08-15"

# Keep your account ID
account_id = "51d2fba458de22279e7ea03fabfa0e62"
workers_dev = true

# Define the SearchPro URL
[vars]
SEARCH_PRO_URL = "https://chat.openai.com/g/g-fdsdf-searchpro"

# Static assets configuration
[site]
bucket = "./public"  # Relative to your project root

# REMOVE THIS ENTIRE SECTION - it's causing the deployment failure
# [[services]]
# binding = "UPSTREAM"
# service = "your-upstream-service"

[placement]
mode = "smart"
